# <font color=3399cc>Numpy Library</font>

In [10]:
import numpy as np


**python objects:** 

1. high-level number objects: integers, floating point
2. containers: lists (costless insertion and append), dictionaries (fast lookup)

**Numpy provides:**

1. extension package to Python for multi-dimensional arrays
2. closer to hardware (efficiency)
3. designed for scientific computation (convenience)
4. Also known as array oriented computing

**Why it is useful:** Memory-efficient container that provides fast numerical operations.

### <font color = red>timeit() is a method in Python library to measure the execution time taken by the given code snippet.</font>

In [2]:
L = range(1000)
%timeit [i**2 for i in L]

218 µs ± 11.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### *Here we are creating a new list i.e.([i***2 for i in L]) and computing all the squares of the values in 'L'

### *And the %timeit function gives the average time to compute the operation*

In [5]:
a = np.arange(1000)
%timeit a**2

1.36 µs ± 90.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### *Now we did this same operation using Numpy and there is a huge difference in their timings*

# Lets create some List

In [11]:
mylist1 = [1,2,3,4]
mylist2 = [5,6,7,8]
mylist3 = [9,10,11,12]


### Now Convert that List datatype into an Array

In [12]:
arr2 = np.array([mylist1,mylist2,mylist3])

In [13]:
type(arr2)

numpy.ndarray

In [15]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

You can explicitly specify which data-type you want:

In [16]:
x = np.arange(10, dtype='float64')
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

Complex datatype

In [18]:
cp = np.array([1+2j, 2+4j]) 
print(cp.dtype)
cp


complex128


array([1.+2.j, 2.+4.j])

In [19]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
s = np.array(['Ram', 'Robert', 'Rahim'])

s.dtype

dtype('<U6')

**Each built-in data type has a character code that uniquely identifies it.**

'b' − boolean

'i' − (signed) integer

'u' − unsigned integer

'f' − floating-point

'c' − complex-floating point

'm' − timedelta

'M' − datetime

'O' − (Python) objects

'S', 'a' − (byte-)string

'U' − Unicode

'V' − raw data (void)

### To check Dimension of an Array

In [22]:
arr2.shape

(3, 4)

### To reshape an Array total numbers always have to match

In [23]:
arr2.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

3D Array

In [24]:
c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])

c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

<b>ndim</b> gives the dimention of the Array

In [25]:
c.ndim

3

In [26]:
c.shape

(2, 2, 2)

# <font color= FF00AA>Indexing<font>

In [27]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])

In [28]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr1[5]

6

In [30]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
arr2[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [32]:
s = np.array([3,2,5,8,1])
s.min()

1

In [33]:
s.max()


8

In [34]:
s.argmin() #It returns the index of the minimum value

4

In [35]:
s.argmax() #It returns the index of the maximum value

3

## To pick up values in a range

In [36]:
arr1 = np.arange(0,9, step = 2)
arr1

array([0, 2, 4, 6, 8])

## If we want values in a specific range

In [37]:
np.linspace(0,10,40)

array([ 0.        ,  0.25641026,  0.51282051,  0.76923077,  1.02564103,
        1.28205128,  1.53846154,  1.79487179,  2.05128205,  2.30769231,
        2.56410256,  2.82051282,  3.07692308,  3.33333333,  3.58974359,
        3.84615385,  4.1025641 ,  4.35897436,  4.61538462,  4.87179487,
        5.12820513,  5.38461538,  5.64102564,  5.8974359 ,  6.15384615,
        6.41025641,  6.66666667,  6.92307692,  7.17948718,  7.43589744,
        7.69230769,  7.94871795,  8.20512821,  8.46153846,  8.71794872,
        8.97435897,  9.23076923,  9.48717949,  9.74358974, 10.        ])

In [38]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

To create Array of all Ones and Zeros

In [39]:

a = np.ones((3, 3))

a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:

a = np.zeros((3, 3))

a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

It return a 2-D array with ones on the diagonal and zeros elsewhere.

In [41]:
b = np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

3 is number of rows, 2 is number of columns, index of diagonal start with 0

In [42]:
b = np.eye(3,2)
b

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

create array using diag function

In [45]:
ab = np.diag([1,2,3,4])
ab

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

Extract diagonal

In [46]:
np.diag(ab)

array([1, 2, 3, 4])

## To <font color=red>Update & Create</font> another Array without changing values of the previous Array

In [47]:
arr4=arr.copy()
print(arr)
arr4[3:] = 100
print(arr4)

[1 2 3 4 5 6]
[  1   2   3 100 100 100]


In [48]:
arr4[arr4<2]

array([1])

In [49]:
arr

array([1, 2, 3, 4, 5, 6])

In [50]:
np.arange(0,4).reshape(2,2)

array([[0, 1],
       [2, 3]])

## In this all the numbers are taken between <font color= red>0 to 1<font>
    
    These are Uniform Distributed Random Numbers

In [51]:
np.random.rand(3,3)

array([[0.38961997, 0.18163637, 0.81489759],
       [0.78309431, 0.55029317, 0.13258113],
       [0.44400767, 0.5887264 , 0.07245578]])

## In this all the numbers are selected acording to <font color= red>Standard Normal Distribution<font>

In [53]:
arr_ex = np.random.randn(3,3)
arr_ex

array([[-0.63729148, -0.10701026,  0.081912  ],
       [-0.35662536,  0.67068914,  0.76585991],
       [ 0.22098028, -1.97399344, -0.4496207 ]])

# <I><font color= FF00AA>Elementwise Operations</font></I>

In [54]:
a = np.array([1,2,3,4,5])
a + 1

array([2, 3, 4, 5, 6])

In [55]:
a ** 2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [56]:
b = np.ones(5) + 1
b

array([2., 2., 2., 2., 2.])

Subtrating Elements of same size Array

In [57]:
a - b

array([-1.,  0.,  1.,  2.,  3.])

In [160]:
a * b

array([ 2.,  4.,  6.,  8., 10.])

## <I><font color= FF00AA>Matrix Multiplication</font></I>

In [58]:
p = np.diag([1,2,3,4])
p

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [59]:
p*p

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [60]:
p.dot(p)  # Another way to multiply Matrix

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

## <I><font color= FF00AA>Matrix Comparison</font></I>

In [61]:
i = np.array([1,2,3,4])
j = np.array([5,3,1,4])
k = np.array([1,2,3,4])


In [62]:
i == j

array([False, False, False,  True])

In [63]:
np.array_equal(i,j)

False

In [64]:
np.array_equal(i,k)

True

In [65]:
i > j

array([False, False,  True, False])

In [66]:
p = np.array([1,2,3]) 
q = np.array([4,5,6])
r = np.array([7,8,9])
((p<=q)&(q<=r)).all()   #Here we compare 3 arrays with each other

True

## <I><font color= FF00AA>Logical Operations</font></I>

In [67]:
a = np.array([1,1,0,0], dtype=bool)
b = np.array([1,0,1,0], dtype=bool)

In [68]:
np.logical_or(a,b)

array([ True,  True,  True, False])

In [69]:
np.logical_and(a,b)

array([ True, False, False, False])

## <I><font color= FF00AA>Transcedental Functions</font></I>

In [70]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [74]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [75]:
np.log(a)

<ipython-input-75-89b6b8e53c58>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [76]:
np.exp(a) #evaluates e^x (e raist to x) for each element in given account

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

## <I><font color= FF00AA>Basic Reductions</font></I>

Computing Sums

In [77]:
x = np.arange(5)
np.sum(x)

10

In [78]:
y = np.array([[1,1],[2,2]])
y

array([[1, 1],
       [2, 2]])

In [79]:
y.sum(axis=0) # It gives sum of columns (first dimention)

array([3, 3])

In [80]:
y.sum(axis=1)  #It gives sum of rows (second dimention)

array([2, 4])

## <I><font color= FF00AA>Stastics</font></I>

In [81]:
x = np.array([1,2,3,1])
y = np.array([[1,2,3],[5,6,6]])

In [82]:
x.mean()  # It returns Average mean of the Array

1.75

In [83]:
np.median(x) # It returns Average median of the Array

1.5

 * Note: 
    * axis = 0 --> Columns
    * axis = 1 --> Rows

In [84]:
np.median(y, axis = 1) #last axis

array([2., 6.])

In [85]:
x.std() # full population standard deviation

0.82915619758885

Example:
    * Data in populations.txt describes the populations of hares and lynxes and carrots in northern Canada during 20 years.
    * e3 = 10^3 (i.e. 1000)

In [86]:
data = np.loadtxt('populations.txt')

In [87]:
data.

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

* Transpose 
    * Transpose means it converts the rows into columns

In [90]:
year, hares, lynxes, carrots = data.T
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [189]:
populations = data[:,1:]
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [190]:
populations.std(axis=0)  # Sample Standard Deviation Columnwise

array([20897.90645809, 16254.59153691,  3322.50622558])

In [191]:
# which species has the highest population each year?

np.argmax(populations, axis=1) 

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)

## <I><font color= FF00AA>Broadcasting</font></I>

Basic operations on numpy arrays (addition, etc.) are elementwise

This works on arrays of the same size.
    Nevertheless, It’s also possible to do operations on arrays of different sizes if NumPy can transform these arrays     so that they all have the same size: this conversion is called broadcasting.

The image below gives an example of broadcasting:

<img src="broadcasting.png" />

In [94]:
a = np.tile(np.arange(0,40,10),(3,1))
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]


In [193]:
a = a.T
print(a)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [194]:
b = np.array([0,1,2])
b

array([0, 1, 2])

In [195]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [196]:
a = np.arange(0,40,10)
a

array([ 0, 10, 20, 30])

In [197]:
a.shape

(4,)

In [198]:
a = a[:,np.newaxis]
np.shape(a)

(4, 1)

In [199]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [200]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

## <I><font color= FF00AA>Array Shape Manipulations</font></I>

### Flatening

* It return a contiguous flattened array. A 1-D array, containing the elements of the input, is returned. A copy is made only if needed.
* Convert 2D array into 1D array.

In [97]:
x = np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [100]:
x.ravel()


array([1, 2, 3, 4, 5, 6])

In [102]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [103]:
x.T.ravel()

array([1, 4, 2, 5, 3, 6])

### Reshaping

* Inverse Operation of Flatening

In [105]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
x.reshape(2,3)


array([[1, 2, 3],
       [4, 5, 6]])

### <font color= red>In this if we dont use <font color= black>copy()</font> then both variable will share same address space because Numpy always try to optimise the Memory Storage and mostly while assigning same data.</font>

In [107]:
y = x.copy()
y

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
x[:1,:1] = 10
x

array([[10,  2,  3],
       [ 4,  5,  6]])

In [109]:
y

array([[1, 2, 3],
       [4, 5, 6]])

### Adding a Dimension

* Indexing with the np.newaxis object allows us to add an axis to an array

* Newaxis is used to increase the dimension of the existing array by one more dimension, when used once.

    * 1D array will become 2D array

    * 2D array will become 3D array

    * 3D array will become 4D array and so on

In [110]:
z = np.arange(0,4)
z

array([0, 1, 2, 3])

In [111]:
z[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3]])

Diamension Shuffling

In [112]:
a = np.arange(4*3*2).reshape(4,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [113]:
a[1,1,1]

9

### Resizing

In [114]:
a = np.arange(4)
a.resize(8,)
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [120]:
b = a
b.resize(4)
print(b)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [216]:
c = np.resize(a,4)
print(c)

[0 1 2 3]


### Sorting Data

Sorting Data Row wise

In [217]:
a = np.array([[5,2,1],[3,4,0]])
a.sort(axis=1)
a

array([[1, 2, 5],
       [0, 3, 4]])

In [218]:
b = np.sort(a,axis=0)
b

array([[0, 2, 4],
       [1, 3, 5]])

In [121]:
m = np.array([5,4,0,1,3,2])

In [122]:
n = np.argsort(m)
n

array([2, 3, 5, 4, 1, 0], dtype=int64)

In [123]:
n[m]

array([0, 1, 2, 3, 4, 5], dtype=int64)