# <font color=red>Numpy Library</font>

In [53]:
import numpy as np


### Lets create some List

In [4]:
mylist1 = [1,2,3,4]
mylist2 = [5,6,7,8]
mylist3 = [9,10,11,12]


### Now Convert that List datatype into an Array

In [6]:
arr2 = np.array([mylist1,mylist2,mylist3])

In [7]:
type(arr2)

numpy.ndarray

In [9]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### To check Dimension of an Array

In [13]:
arr2.shape

(3, 4)

### To reshape an Array total numbers always have to match

In [18]:
arr2.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# <font color= red>Indexing<font>

In [19]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])

In [20]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr1[5]

6

In [19]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
arr2[0:2,0:2]

array([[1, 2],
       [5, 6]])

## To pick up values in a range

In [21]:
arr1 = np.arange(0,9, step = 2)
arr1

array([0, 2, 4, 6, 8])

## If we want values in a specific range

In [22]:
np.linspace(0,10,40)

array([ 0.        ,  0.25641026,  0.51282051,  0.76923077,  1.02564103,
        1.28205128,  1.53846154,  1.79487179,  2.05128205,  2.30769231,
        2.56410256,  2.82051282,  3.07692308,  3.33333333,  3.58974359,
        3.84615385,  4.1025641 ,  4.35897436,  4.61538462,  4.87179487,
        5.12820513,  5.38461538,  5.64102564,  5.8974359 ,  6.15384615,
        6.41025641,  6.66666667,  6.92307692,  7.17948718,  7.43589744,
        7.69230769,  7.94871795,  8.20512821,  8.46153846,  8.71794872,
        8.97435897,  9.23076923,  9.48717949,  9.74358974, 10.        ])

In [23]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

## To <font color=red>Update & Create</font> another Array without changing values of the previous Array

In [25]:
arr4=arr.copy()
print(arr)
arr4[3:] = 100
print(arr4)

[1 2 3 4 5 6]
[  1   2   3 100 100 100]


In [26]:
arr4[arr4<2]

array([1])

In [106]:
arr

array([1, 2, 3, 4, 5, 6])

In [111]:
np.arange(0,4).reshape(2,2)

array([[0, 1],
       [2, 3]])

## In this all the numbers are taken between <font color= red>0 to 1<font>

In [123]:
np.random.rand(3,3)

array([[0.23388551, 0.1488164 , 0.70589891],
       [0.56576137, 0.30512412, 0.09712742],
       [0.22134243, 0.69050406, 0.24963694]])

## In this all the numbers are selected acording to <font color= red>Standard Normal Distribution<font>

In [52]:
arr_ex = np.random.randn(3,3)
arr_ex

array([[-1.33794954, -0.70074908, -0.07248614],
       [-0.08002634, -1.63287449, -1.13388098],
       [ 0.23846468, -0.02733574, -2.26329432]])